### ISSUE TITLE
Cannot find module "raven"

### ISSUE THREAD

**Issue by andresgutgon** [mike-engel/Barnacal#6]
## What?
I see this when I try to run the calendar after lates update
![image](https://user-images.githubusercontent.com/49499/63155434-d52dbe80-c012-11e9-8fff-ce9a738595e9.png)

Any ideas?

Look like Sentry code is not loaded :)

**Comment by mike-engel** [comment]
I missed an old `require` to the old sentry module. This is fixed in `0.9.1`, but since this occurred in the `auto-updater` file, you'll probably need to download and re-install Barnacal. https://github.com/mike-engel/Barnacal/releases/tag/v0.9.1

**Comment by andresgutgon** [comment]
Great looks fixed after update to 0.9.1 🎉
